### ISSUE TITLE
SubScript Error while Scanning Library

### ISSUE THREAD

**Issue by Kureigu07** [CogentHub/HomeLoader#2]
> Autolt Error
> 
> Line 26093 (File
> "~\HomeLoader.exe"):
> 
> Error: Subscript used on non-accessible variable.

I can resolve this by deleting the HomeLoader folder, and re-extracting it from the Zip.

**Comment by CogentHub** [comment]
Thanks for reporting. Saw it too late, my bad. A lot changed since 0.75, please try again. It should be fixed. I need to set notifications to get aware of the reporting issues.

**Comment by CogentHub** [comment]
I have released a new version, HomeLoader 0.77. Please try the new version. Before you run it for the first time please activate the debug mode in config.ini File for further investigation. Change the Value "Debug_Mode=false" to "true". It's at the beginning of the config.ini File at the fifth line. If you get the error again then backup all four log Files before you try to start HomeLoader again and send them to me. If you don't get an error then you can set "Debug_Mode=false" to false again.

**Comment by Kureigu07** [comment]
I've emailed my log files to you. If you require any more information, such as dxdiag or software/driver version please let me know.

**Comment by CogentHub** [comment]
Hello,


thanks for the Files.
They are helpful, that way I can see what it has done and what was the last thing it tried to do.
The problem is that I cannot use the line number from the normal error message due to some design decision I made.
Therefore I need some other way to get them and that's why I added the "debug mode" with these log Files.

But important is to backup the log files directly after the error appears.
You can set "Debug_Mode=true" in the config.ini File to get more log outputs.
Asuming that you already did that and looking at the log Files I would sag it crashed during updating of the Icons.
Try the following:
- Disable checkbox "Request Steamdb Info
- Disable checkbox "Request Steamdb Tags

Try again with "Debug_Mode=true in t he config.ini File.
There are now two with that issues, at least two that I know from.
Hope I can find and fix it soon.

**Comment by ghost** [comment]
I'm getting this error too, I'll shoot the logs over your way.

I also tried disabling those two checkboxes but that didn't fix it.

**Comment by Kureigu07** [comment]
I have been trying out version 0.78 today, the error still persists.
Out of curiosity I also tried in Safe Mode with Networking, and also after having uninstalled a bunch of games.
It does however work fine on another computer that I have, but they are wildly different hardware, and software. Win 10 home, vs Win 10 Pro, i5 8300H, vs i7 3770K etc.

**Comment by CogentHub** [comment]
Hello. In the past I tested it on Windows 7 pro too, it worked. But since some time I can only test it on two different computers, both with Windows 10 pro and Vive Headsets. They also have different Steam account/Game Libraries but with similar games. The first one is were I write it and the second one is the gaming PC were I test the compiled version before release. So never tested an Home version of Windows but I don't think that's were it comes from. Someone else with the same error sent me his log Files and then he uninstalled the last game showed in the last line of the log files, that fixed it for him and it was the Icon 256x256 download (unreleased game on Steam without that Icon on steamdb). I think it was  z0oinks above us. I will write you an E-Mail with some further informations.
